fullnameOverride: sampleapp
replicaCount: 2
image:
  repository: VALUE_TO_BE_OVERRIDDEN
  tag: latest

imagePullSecrets: []
service:
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  path: /
  hostname: VALUE_TO_BE_OVERRIDDEN

secrets: {}
resources: {}
nodeSelector: {}

tolerations: []

affinity: {}

applicationInsights:
  InstrumentationKey: VALUE_TO_BE_OVERRIDDEN
